### ISSUE TITLE
Problems with the tramlines

### ISSUE THREAD

**Issue by IdkMyUse** [stijnwop/proSeed#39]
I used the Vaderstad 400C mod with 24m tramlines, but when i go with a 24 meter wide sprayer, tramlines isnt 24m, its more like 26, so i had to use the 20m tramlines, but then the sprayer is too wide. tell me how to fix it plz(FS19)

**Comment by punchi21** [comment]
If your sprayer width : seeding width = equal number, you need to start with a half width seeding.

**Comment by IdkMyUse** [comment]
okey so 24/4=6, so the first pass should be notcoundet, cuz i go the 6times around the headland and then i do the mid, so then i go the 1pass with half side shut off, the 2 is full, 3 full, 4the tramline, 5, full, 6 full, so 5 and a half passes?

**Comment by punchi21** [comment]
basically the problem is, the tramline needs to be in the middle of 24m which is 12m on each side. that would be 3 passes with a 4m. but since the seeders only do tramlines in the center of their working  width, its not possible to put a tramline at 12m when going full width.
so 1pass halfside 2/3 full, 4 tramline is correct. also only the very first pass has to be half, then you can let the semi automatic/gps counter do the rest

**Comment by IdkMyUse** [comment]
thank you

**Comment by KITT3000** [comment]
you just had to look here https://github.com/stijnwop/proSeed/blob/master/docs/ProSeed.pdf

**Comment by IdkMyUse** [comment]
well if i could understand german tht would be good

**Comment by stijnwop** [comment]
Second page is English ;)
